services:
  typesense:
    image: typesense/typesense:latest
    ports:
      - "8108:8108"
    volumes:
      - ./data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    restart: unless-stopped