
# comma delimited
# 3,a,aco,adv,an,b,bant,biz,c,cgl,ck,cm,co,d,diy,e,f,fa,fit,g,gd,gif,h,hc,his,hm,hr,i,ic,int,jp,k,lgbt,lit,m,mlp,mu,n,news,o,out,p,po,pol,pw,qa,qst,r,r9k,s,s4s,sci,soc,sp,t,tg,toy,trv,tv,u,v,vg,vip,vm,vmg,vp,vr,vrpg,vst,vt,w,wg,wsg,wsr,x,xs,y

# space delimited
# 3 a aco adv an b bant biz c cgl ck cm co d diy e f fa fit g gd gif h hc his hm hr i ic int jp k lgbt lit m mlp mu n news o out p po pol pw qa qst r r9k s s4s sci soc sp t tg toy trv tv u v vg vip vm vmg vp vr vrpg vst vt w wg wsg wsr x xs y

[boards]
3 = '3DCG'
a = 'Anime & Manga'
aco = 'Adult Cartoons'
adv = 'Advice'
an = 'Animals & Nature'
b = 'Random'
bant = 'International/Random'
biz = 'Business & Finance'
c = 'Anime/Cute'
cgl = 'Cosplay & EGL'
ck = 'Food & Cooking'
cm = 'Cute/Male'
co = 'Comics & Cartoons'
d = 'Hentai/Alternative'
diy = 'Do It Yourself'
e = 'Ecchi'
f = 'Flash'
fa = 'Fashion'
fit = 'Fitness'
g = 'Technology'
gd = 'Graphic Design'
gif = 'Adult GIF'
h = 'Hentai'
hc = 'Hardcore'
his = 'History & Humanities'
hm = 'Handsome Men'
hr = 'High Resolution'
i = 'Oekaki'
ic = 'Artwork/Critique'
int = 'International'
jp = 'Otaku Culture'
k = 'Weapons'
lgbt = 'LGBT'
lit = 'Literature'
m = 'Mecha'
mlp = 'Pony'
mu = 'Music'
n = 'Transportation'
news = 'Current News'
o = 'Auto'
out = 'Outdoors'
p = 'Photo'
po = 'Papercraft & Origami'
pol = 'Politically Incorrect'
pw = 'Professional Wrestling'
qa = 'Question & Answer'
qst = 'Quests'
r = 'Adult Requests'
r9k = 'ROBOT9001'
s = 'Sexy Beautiful Women'
s4s = 'Shit 4chan Says'
sci = 'Science & Math'
soc = 'Cams & Meetups'
sp = 'Sports'
t = 'Torrents'
tg = 'Traditional Games'
toy = 'Toys'
trv = 'Travel'
tv = 'Television & Film'
u = 'Yuri'
v = 'Video Games'
vg = 'Video Game Generals'
vip = 'Very Important Posts'
vm = 'Video Games/Multiplayer'
vmg = 'Video Games/Mobile'
vp = 'Pokemon'
vr = 'Retro Games'
vrpg = 'Video Games/RPG'
vst = 'Video Games/Strategy'
vt = 'Virtual YouTubers'
w = 'Anime/Wallpapers'
wg = 'Wallpapers/General'
wsg = 'Worksafe GIF'
wsr = 'Worksafe Requests'
x = 'Paranormal'
xs = 'Extreme Sports'
y = 'Yaoi'