[boards]
'λ' = 'Programming'
'Ω' = 'Technology'
'Δ' = 'Do It Yourself'
'sec' = 'Security'
'inter' = 'Games and Interactive Media'
'lit' = 'Literature'
'music' = 'Musical and Audible Media'
'vis' = 'Visual Media'
'hum' = 'Humanity'
'drg' = 'Drugs 3.0'
'zzz' = 'Consciousness and Dreams'
'layer' = 'layer'
'q' = 'Questions and Complaints'
'r' = 'Random'