[app]
testing = false
secret = 'DEFAULT_CHANGE_ME' # python -c "import secrets as s; print(s.token_hex(24))"
validate_boards_db = true
autoreload = false

# quart/hypercorn keys
port = 9001
# ssl_key = 'key.pem'
# ssl_cert = 'cert.pem'

[site]
name = 'Ayase Quart'
theme = 'tomorrow' # 'tomorrow' 'yotsuba' 'yotsuba_b' 'futaba' 'burichan' 'photon'

[db]
db_type = 'mysql' # mysql, sqlite, postgresql
echo = false # print rendered sql statements to console if enabled

[db.mysql] # follow pymysql/aiomysql connection keys
host = '127.0.0.1'
port = 3306
# unix_socket = '/var/run/mysqld/mysqld.sock'
db = 'asagi'
user = 'asagi'
password = 'asagi'
minsize = 1
maxsize = 50

[db.sqlite] # follow aiosqlite connection keys
database = 'path/to/file.db'

[db.postgresql] # follow aiosqlite connection keys
host = 'localhost' # also used for unix domain socket
port = 5432
user = 'asagi'
password = 'asagi'
database = 'asagi'
min_size = 1
max_size = 50

[redis] # follow coredis connection keys
host = "127.0.0.1"
port = 6379
db = 0


[media]
image_uri = "https://192.168.1.16:9003/static/ritual/{board_shortname}/image" # must contain {board_shortname}
thumb_uri = "https://192.168.1.16:9003/static/ritual/{board_shortname}/thumb" # must contain {board_shortname}

# these optional settings are for serving media outside the quart app static path
# i.e. outside of '/path/to/ayase_quart/src/static'
serve_outside_static = false # true, false
media_root_path = '' # the full path to the root media directory on your server e.g. '/mnt/dl' where there exists paths like '/mnt/dl/<board_shortname>/image'
valid_extensions = ['jpg', 'jpeg', 'png', 'gif', 'webm', 'mp4']
endpoint = '/serve/abc/' # serves content from filesystem at endpoint /serve/abc/<board_shortname>/image
# if you use this, the following must be done:
# image_uri = "/<endpoint>/{board_shortname}/image" # must contain {board_shortname}
# thumb_uri = "/<endpoint>/{board_shortname}/thumb" # must contain {board_shortname}
# e.g.
# image_uri = "/serve/abc/{board_shortname}/image" # must contain {board_shortname}
# thumb_uri = "/serve/abc/{board_shortname}/thumb" # must contain {board_shortname}
# and comment out the other image_uri, thumb_uri configs.


[search]
enabled = true
highlight = true
hits_per_page = 500
max_hits = 10000
provider = 'lnx' # lnx, meili, manticore, typesense, quickwit
host = 'http://localhost:8000'

[search.config]
headers = { content-type = 'application/json' }

[search.meili]

[search.lnx]

[moderation]
moderation = true # true, false
admin_user = 'admin'
admin_password = 'admin'
default_reported_post_status = 'hidden' # visible, hidden, deleted
hide_delete_posts = true # hide 4chan staff deleted posts in archive
memcache = true # true, false
memcache_type = 'sqlite' # sqlite, bloom

[moderation.sqlite]
database = 'moderation.db'